#!/bin/bash
echo "Chords Music Academy CRM System"
echo "================================"
echo ""
echo "To run this application:"
echo "1. Install Python dependencies:"
echo "   python3 -m pip install streamlit pandas qrcode Pillow openpyxl requests"
echo ""
echo "2. Run the application:"
echo "   streamlit run app.py"
echo ""
echo "3. Login credentials:"
echo "   Username: admin"
echo "   Password: password123"
echo ""
echo "The application will open in your web browser at http://localhost:8501"